title: Jessica Gerner
#logo
description: PhD Student in Clinical Psychology | The Catholic University of America
#show_downloads:true
theme: jekyll-theme-minimal
logo: /assets/img/Gerner_headshot_sept2025.png
cv: /assets/files/Jessica_Gerner_CV.pdf
