title: Jessica Gerner
#logo
description: >
  Clinical Psychology Ph.D. Candidate<br>
  <a href="/assets/files/Jessica_Gerner_CV.pdf">Download CV</a>
#show_downloads:true
theme: jekyll-theme-minimal
logo: /assets/img/Gerner_headshot_sept2025.png

